blueprint:
  name: Sync Custom Brightness
  description: >-

    [![Open your Home Assistant instance and show the blueprint import dialog with a specific blueprint pre-filled.](https://my.home-assistant.io/badges/blueprint_import.svg)](https://my.home-assistant.io/redirect/blueprint_import/?blueprint_url=https%3A%2F%2Fraw.githubusercontent.com%2Fjnrcorp%2Fha-blueprints%2Fmain%2Fha-blueprint-sync-custom-brightness.yaml)

    **Sync Brightness to Z-Wave Attribute v1.0**

    This blueprint allows you to easily create/maintain an automation that links the state of multiple entities:
      - set the brightness of any Z-Wave dimmer switch entity, it will set the custom brightness z-wave attribute to that brightness.
        - For Zooz, this is Custom Brightness.
        - For Leviton, this is Initial Brightness.

    **NOTE**: You can select any device and this script will not verify what you provide is accurate, but it will fail if the device is not compatible.

    **CHANGELOG:**
      - 1.0: (2025-01-13)
        - First official release

  domain: automation
  input:
    dimmer_switch_entity:
      name: Z-Wave Dimmer Switch Entities
      description: Entities whose custom brightness attribute will be updated each time the brightness on the switch is updated.
      selector:
        entity:
          multiple: true
    delay_miliseconds:
      name: Delay
      description: How long to delay changes to the custom brightness attribute
      selector:
        number:
          min: 0
          max: 1000
          unit_of_measurement: miliseconds
          mode: box
      default: 200
    zwave_command_class:
      name: Z-Wave Command Class
      description: For me, this has been 112 for both Leviton and Zooz switches.
      selector:
        number:
          min: 0
          mode: box
      default: 112
    zwave_property:
      name: Z-Wave Property
      description: You'll need to check your specific device to find which property # you are trying ot adjust. It should be in the specifications. Zooz ZEN72 and ZEN77 are 18 and Leviton DZ6HD is 5
      selector:
        number:
          min: 0
          mode: box
      default: 18
    max_brightness_value:
      name: Maximum Brightness Value for the Z-Wave Property
      description: This will probably be 99 or 100 depending on the device. Zooz devices seem to be 99 and Leviton seem to be 100.
      selector:
        number:
          min: 0
          mode: box
      default: 99

mode: single
max_exceeded: silent

variables:
  dimmer_switch_entities: !input dimmer_switch_entity

trigger:
  - platform: state
    id: set_brightness
    entity_id: !input dimmer_switch_entity
    attribute: brightness
  - platform: state
    id: turn_on
    entity_id: !input dimmer_switch_entity
    to: "on"

condition:
  - condition: template
    value_template: "{{ trigger.to_state.attributes.brightness != None }}"

actions:
  - sequence:
    - variables:
        max_brightness: !input max_brightness_value
        set_light_brightness: "{{ trigger.to_state.attributes.brightness / 255 * max_brightness | round(0) }}"
    - delay:
        milliseconds: !input delay_miliseconds
    - action: zwave_js.set_value
      metadata: {}
      data:
        command_class: !input zwave_command_class
        property: !input zwave_property
        value: "{{ set_light_brightness }}"
        entity_id: "{{ trigger.entity_id }}"
